### ISSUE TITLE
can you update latedt version as i can see on play store

### ISSUE THREAD

**Issue by rajkiranjeet** [lp1dev/smartlight-manager#1]
if its paid work let us know we can deal as well

**Comment by lp1dev** [comment]
Good evening! If I understand correctly what you need, you want to download the app on the Play Store?

**Comment by rajkiranjeet** [comment]
Hi
is it same app
https://play.google.com/store/apps/details?id=com.jellyfishtur.multylamp.WIFI_Multy_dianshang
as i can see its update version ,if its same can you update github code

**Comment by lp1dev** [comment]
It is not the same app. The one you're referring to is the official iHomma application.
